server:
  port: 8081
##  context-path: /dock
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.163.com
    username: ${email}
    password: ${email_token}
    default-encoding: UTF-8



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql_url}
    username: ${mysql_username}
    password: ${mysql_password}
    datasourcetype: com.alibaba.druid.pool.DruidDataSource


logging:
  level:
    com:
      egzosn: debug
  file: examples.log

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库类型
      db-type: MYSQL
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true

app:
  url: &app.url http://localhost:8081
file:
  uploadPath: &file.uploadPath images/
  directoryMapping: /xechat/
  staticAccessPath: /**
  accessAddress: http://localhost:8081/images/
chatrecord:
  path: ${chatrecord_path}
  accessAddress: http://localhost:8081/chatrecord/
  password: ${chatrecord_password}

restTemplate:
  threadSize: 20
  waitingTime: 500
  connectTimeOut: 10000
  readTimeOut: 10000
turing:
  apiUrl: http://openapi.tuling123.com/openapi/api/v2
  apiKey:

rsa:
  publicKey: ${ras_publicKey}
  privateKey: ${ras_privateKeyKey}

kuaidi100:
  key: ${kuaidi100_key}
  customer: ${kuaidi100_customer}














